name = "lapce-python"
display-name = "Python"
description = "Python for Lapce: powered by https://github.com/python-lsp/python-lsp-server"
version = "0.3.1"
author = "various"
repository = "superlou/lapce-python"
wasm = "lapce-python.wasm"

[configuration]
language_id = "python"
# lsp_exec="/path/to/lsp/executable" # Full path or name on PATH

[configuration.options]
# Options passed to the LSP server
