name = "lapce-python"
display-name = "Python"
description = "Python for Lapce: powered by https://github.com/python-lsp/python-lsp-server"
version = "0.1.0"
author = "various"
repository = "superlou/lapce-python"
wasm = "lapce-python.wasm"

[configuration]
# Hack to avoid needing to specify absolute path to pyls
env_command = "echo \"PYLSP_PATH=$(which pylsp)\""
# language_id may not matter to lapce yet
language_id = "python"
# options not passed to plugin?
options = ["--log-file", "./pylsp.txt"]
