name = "lapce-python"
display-name = "Python"
description = "Python for Lapce: powered by https://github.com/python-lsp/python-lsp-server"
version = "0.2.0"
author = "various"
repository = "superlou/lapce-python"
wasm = "lapce-python.wasm"

[configuration]
# language_id may not matter to lapce yet
language_id = "python"
# options not passed to plugin?
options = ["--log-file", "./pylsp.txt"]
