name = "lapce-python"
version = "0.3.2"
author = "various"
display-name = "Python (python-lsp-server)"
description = "Python for Lapce using python-lsp-server"
wasm = "lapce-python.wasm"
icon = "python-logo-only.png"

[activation]
language = ["python"]
